name: biedronka_expenses
description: "Biedronka PDF receipt tracking - MVP. All processing on device."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.0.0
  path: ^1.9.0
  fl_chart: ^0.70.1
  file_picker: ^8.1.4
  workmanager: ^0.6.0
  sentry_flutter: ^8.12.0
  intl: ^0.20.1
  collection: ^1.19.0
  crypto: ^3.0.6
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/sample_receipt.txt
    - assets/test/receipts/sample.pdf
    - assets/test/receipts/broken.pdf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/RB_icon.png
  remove_alpha_ios: true
