name: Android Debug APK

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-debug:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      PROJECT_DIR: .
      JP2_AAR_URL: ${{ secrets.JP2_AAR_URL }}
      JP2_AAR_SHA256: ${{ secrets.JP2_AAR_SHA256 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.3"
          channel: "stable"

      - name: Flutter pub get
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter pub get

      - name: Build debug APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter build apk --debug

      - name: Upload artifact (app-debug.apk)
        uses: actions/upload-artifact@v4
        with:
          name: biedronka_expenses-debug-${{ github.sha }}
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: error
          retention-days: 4
